# Generated by Django 6.0.4 on 2026-05-14 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('listing_type', models.CharField(choices=[('for_sale', 'For Sale'), ('for_rent', 'For Rent')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('active', 'Active'), ('sold', 'Sold'), ('rented', 'Rented'), ('archived', 'Archived'), ('deactivated', 'Deactivated')], max_length=20)),
                ('property_type', models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('flat', 'Flat'), ('villa', 'Villa'), ('plot', 'Plot'), ('commercial', 'Commercial')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('price_negotiable', models.BooleanField(default=False)),
                ('area_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('area_unit', models.CharField(choices=[('sqft', 'Square Feet'), ('marla', 'Marla'), ('kanal', 'Kanal'), ('sqyd', 'Square Yard')], max_length=20)),
                ('bedrooms', models.PositiveIntegerField(null=True)),
                ('bathrooms', models.PositiveIntegerField(null=True)),
                ('floor_number', models.PositiveIntegerField(null=True)),
                ('furnishing_status', models.CharField(choices=[('furnished', 'Furnished'), ('semi_furnished', 'Semi Furnished'), ('unfurnished', 'Unfurnished'), ('not_applicable', 'Not Applicable')], max_length=50, null=True)),
                ('noc_status', models.CharField(choices=[('available', 'Available'), ('pending', 'Pending'), ('not_applicable', 'Not Applicable')], max_length=50, null=True)),
                ('city', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('description', models.TextField()),
                ('is_featured', models.BooleanField(default=False)),
                ('featured_since', models.DateTimeField(blank=True, null=True)),
                ('featured_until', models.DateTimeField(blank=True, null=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sold_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
