# Generated by Django 6.0.4 on 2026-07-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='agency_logo',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='agency_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_verified_agent',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='license_document',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='license_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='verified_at',
        ),
        migrations.AddField(
            model_name='customuser',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('admin', 'Admin')], default='buyer', max_length=20),
        ),
    ]
